# Generated by Django 3.0.3 on 2020-02-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('gender', models.CharField(choices=[('М', 'Мальчик'), ('Д', 'Девочка')], max_length=2)),
                ('image', models.ImageField(upload_to='%Y/%m/%d/')),
                ('size', models.CharField(choices=[('3T', '3 года'), ('4T', '4 года'), ('5T', '5 лет'), ('6T', '6 лет'), ('7T', '7 лет')], max_length=2)),
                ('date_publish', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
